"""esquema inicial

Revision ID: fb01695637ae
Revises: 
Create Date: 2026-08-25 23:30:30.165994

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'fb01695637ae'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('miembros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('apellidos', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('fecha_registro', sa.Date(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_miembros_apellidos'), 'miembros', ['apellidos'], unique=False)
    op.create_index(op.f('ix_miembros_email'), 'miembros', ['email'], unique=False)
    op.create_index(op.f('ix_miembros_nombre'), 'miembros', ['nombre'], unique=False)
    op.create_table('planes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duracion_dias', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planes_nombre'), 'planes', ['nombre'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('rol', sa.Enum('ADMIN', 'RECEPCION', name='rolusuario'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('suscripciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('miembro_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('precio_pagado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('creada_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['miembro_id'], ['miembros.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['planes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suscripciones_fecha_fin'), 'suscripciones', ['fecha_fin'], unique=False)
    op.create_index(op.f('ix_suscripciones_miembro_id'), 'suscripciones', ['miembro_id'], unique=False)
    op.create_index(op.f('ix_suscripciones_plan_id'), 'suscripciones', ['plan_id'], unique=False)
    op.create_table('asistencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('miembro_id', sa.Integer(), nullable=False),
    sa.Column('registrada_en', sa.DateTime(), nullable=False),
    sa.Column('suscripcion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['miembro_id'], ['miembros.id'], ),
    sa.ForeignKeyConstraint(['suscripcion_id'], ['suscripciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asistencias_miembro_id'), 'asistencias', ['miembro_id'], unique=False)
    op.create_index(op.f('ix_asistencias_registrada_en'), 'asistencias', ['registrada_en'], unique=False)
    op.create_index(op.f('ix_asistencias_suscripcion_id'), 'asistencias', ['suscripcion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asistencias_suscripcion_id'), table_name='asistencias')
    op.drop_index(op.f('ix_asistencias_registrada_en'), table_name='asistencias')
    op.drop_index(op.f('ix_asistencias_miembro_id'), table_name='asistencias')
    op.drop_table('asistencias')
    op.drop_index(op.f('ix_suscripciones_plan_id'), table_name='suscripciones')
    op.drop_index(op.f('ix_suscripciones_miembro_id'), table_name='suscripciones')
    op.drop_index(op.f('ix_suscripciones_fecha_fin'), table_name='suscripciones')
    op.drop_table('suscripciones')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_planes_nombre'), table_name='planes')
    op.drop_table('planes')
    op.drop_index(op.f('ix_miembros_nombre'), table_name='miembros')
    op.drop_index(op.f('ix_miembros_email'), table_name='miembros')
    op.drop_index(op.f('ix_miembros_apellidos'), table_name='miembros')
    op.drop_table('miembros')
    # ### end Alembic commands ###
